using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/*
    This script handles the particle systems generated by Alucard's W effect
*/
/// <summary>
/// This script handles the particle systems generated by Alucard's W effect.
/// </summary>
public class AlucardW_Effect : MonoBehaviour {

    // Private variables
    PhotonView photonView;
    PhotonPlayer attacker;
    float damageBase;
    int attackerIdBase;

    /// <summary>
    /// Initialises the particle system on the network and deals damage.
    /// </summary>
    /// <param name="radius">The radius of the attack circle</param>
    /// <param name="damage">The damage dealt by the ability</param>
    /// <param name="direction">The direction of the ability</param>
    /// <param name="attackerId">The ID of the player performing the ability</param>
    public void Init(float radius, float damage, Vector3 direction, int attackerId) {
        photonView = GetComponent<PhotonView>();
        photonView.RPC("InitRPC", PhotonTargets.AllBuffered, radius, damage, direction, attackerId);
    }

    // Initialise the effect on the network
    [PunRPC]
    void InitRPC(float radius, float damage, Vector3 direction, int attackerId) {
        attackerIdBase = attackerId;
        attacker = PhotonView.Find(attackerId).owner;
        damageBase = damage;
        gameObject.transform.LookAt(direction);

        if (PhotonNetwork.isMasterClient)
            StartCoroutine("Delete");
    }

    // Called by AlucardW_Trigger by the Master Client
    public void OnTrigger(Entity entity) {
        PhotonView targetView = entity.GetComponent<PhotonView>();
        PhotonPlayer target = targetView.owner;
        if (entity.team != attacker.GetTeam()) {
            if (entity.GetComponent<PlayerChampion>() != null)
                targetView.RPC("Damage", PhotonTargets.AllBuffered, damageBase, attackerIdBase);
            else if (entity.GetComponent<Minion>() != null)
                targetView.RPC("EntityDamage", PhotonTargets.AllBuffered, damageBase, attackerIdBase);
        }
    }

    // Destroy the particle effects after time
    IEnumerator Delete() {
        yield return new WaitForSeconds(1.5f);
        PhotonNetwork.Destroy(gameObject);
    }
}